apiVersion: v1
kind: Pod
metadata:
  name: fullstack-app
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: frontend
      image: nginx
    - name: backend
      image: busybox
